### PR TITLE
Equalizer

### PR DESCRIPTION
**Pull request by rkralovic**

### CODE REVIEW

**Comment by hselasky** [comment]
OK, I see. Try to squash the patches together when you're done.

**Comment by hselasky** [comment]
If you want quality try to use this multiplication transform instead of the FFT one:
https://github.com/hselasky/qaudiosonar/blob/master/qaudiosonar_mul.cpp

**Comment by rkralovic** [comment]
Squashed.

Is there any documentation on what qas_x3_multiply_double actually does and why it is better than using FFT to calculate convolution?

**Comment by hselasky** [comment]
The function qas_x3_multiply_double() does not suffice the problems of using a sine-wave transform, because qas_x3_multiply_double() uses a set of square waves instead to do the fast multiplication // correlation. There is not more documentation than source code :-) Something that resulted as a product of hobby math research :-)

**Comment by rkralovic** [comment]
Ok, I'll try to read the code more carefully, but it seems it will take some time :-).

Otoh, I think that FFT should work well in my case: I precalculate the frequency domain filter such that it is identical to a FIR filter with very close frequency response as the requested one. Then, the numerical error of FFT should be negligible for actually calculating the FIR result.

**Comment by hselasky** [comment]
It is not so much about error. It is more about that certain waveforms make the FFT unstable.

**Comment by rkralovic** [comment]
That sounds interesting - could you plz. share some more pointers about
that? I am wondering if there really is an input where convolution
calculated via FFT gives different numerical results than exact calculation
after rounding to 24 most significant bits.

**Comment by hselasky** [comment]
You might be right that the error won't be so big or easily noticable, but the problem is that you need more and more different angles as the transform grows bigger and remember you have to divide the result by N, which is the size of the FFT. The mantissa of a float is 24-bit, so you will in worst case have to subtract log2(N) which give you the real number of bits. Let's say you use 1024 samples for a FFT 32-bit floating point, then in practice you are reducing the sample size to 24-10 = 14 bits. This might be good enough for most purposes, but there _is_ a difference between 14-bit and 24-bit audio.

Try searching for "Roundoff Error Analysis of the Fast Fourier Transform" on Google.

**Comment by rkralovic** [comment]
Sure, floats are way too unprecise. That's why all floating point
calculations are done in doubles, which have 52 bit fraction. Even when
using 64k window size, there are only 16 bits of error introduced, which
gives still 36 bits of result, i.e., there are still 8 error-free bits
thrown away when rounding to 24bit precision. Accuracy benchmarks of fftw3 (
http://www.fftw.org/accuracy/index.html ) also show that the error is way
below 1 in 24bit depth.

But your algorithm (qas_x3_multiply_double) looks interesting, however, I
still didn't get what it actually does. What are the input values (va, vb)?
Does it calculate a circular convolution or something else? What is its
time complexity? (I see 3 recursive calls for halving the stride, which
suggest O(n^log_2(3)) ~ O(n^1.58), if it is so, it is also quite slower
than FFT.)

**Comment by hselasky** [comment]
qas_x3_multiply_double() needs 3**N . For example table size = 1024.

FFT 2radix needs 10 * 1024 = 10 complex multiplications ,  which results in 40 K multiplications.

Now, 3**10 non-complex multiplications is ~60 K multiplications. Given reduced memory footprint and complexity this isn't so bad. Also the accuracy gain weighs in.

Can you try to use the support I've added in:
https://github.com/hselasky/virtual_oss/commit/e35334d9e7718ed6b5e416f7b46cd1dfe477e322

Simply set the tx_filter_size or rx_filter_size in the profile to a power of two value and allocate the impulse response in the corresponding double pointers I've added.

**Comment by hselasky** [comment]
BTW: I didn't have time to test this new support, so there might be a bug or two to fix.

**Comment by rkralovic** [comment]
Thanks for the patch!

On Sat, Mar 9, 2019 at 1:55 PM HPS <notifications@github.com> wrote:

> qas_x3_multiply_double() needs 3**N . For example table size = 1024.
>
> FFT 2radix needs 10 * 1024 = 10 complex multiplications , which results in
> 40 K multiplications.
>
> Now, 3**10 non-complex multiplications is ~60 K multiplications. Given
> reduced memory footprint and complexity this isn't so bad. Also the
> accuracy gain weighs in.
>
Well, for N=12 (block size 4096, which is reasonable to achieve reasonable
bass resolution) it is already 12*4096=49k vs. 3**12=531k - more than 10x.
And I am still not convinced that there are actually any accuracy gains.
(Perhaps I should try to compare both approaches and see if the output is
exactly the same.)

If the input impulse response is already rounded to integers, we could use
number-theoretic transform (FFT over a finite field, i.e., arithmetic
modulo prime). But the mixing is already done in doubles, and also rounding
the input response to integers means extra precision loss.


> Can you try to use the support I've added in:
> e35334d
> <https://github.com/hselasky/virtual_oss/commit/e35334d9e7718ed6b5e416f7b46cd1dfe477e322>
>
> Simply set the tx_filter_size or rx_filter_size in the profile to a power
> of two value and allocate the impulse response in the corresponding double
> pointers I've added.
>
To do so, I would have to add some support to receive the impulse response
over the control socket? That would be actually nice, however, I would not
call the thing 'equalizer' any more, since it is a general FIR filter that
can be used to other purposes than equalization. Also, keeping the impulse
response as doubles could make more sense than rounding to integers?

**Comment by rkralovic** [comment]
Actually, there is one more concern: If I understand correctly, the actual
latency of virtual_oss with buffer of B samples is about 3*B - 4*B (there
is the input buffer where CUSE writes, that one is resampled into the
buffer from which main loop reads and mixes into the output buffer, which
is then resampled to the actual output from which CUSE sends data to the
client app, and all these buffers have B samples). That means that with
B=4096 (which I currently use for equalization), the latency will be about
300ms instead of 100ms (what I currently have).

**Comment by hselasky** [comment]
The size of the FIR transform is independent of the buffer size used. At least in my implementation.

4K FIR means a delay of 4K/48000 = 85 ms at 48Khz. Then comes the buffering size in addition.

**Comment by hselasky** [comment]
I'm planning to add an IOCTL for the control interface of virtual_oss to update those FIR filters.
Further it should be trivial to add a "virtual_equalizer" app which has input 5 simple controllable filters, which generate the needed FIR filter?

1) Which frequency
2) Sharpness
3) Low-pass or High-pass or Band-pass

--HPS

**Comment by hselasky** [comment]
> Well, for N=12 (block size 4096, which is reasonable to achieve reasonable bass resolution) it is already 12*4096=49k vs. 3**12=531k - more than 10x. And I am still not convinced that there are actually any accuracy gains. (Perhaps I should try to compare both approaches and see if the output is exactly the same.)

You forgot that FFT uses 4x number of multiplications.

4 * 12 * 4096=196k VS 3**12=531k      SO roughly 2x. And I don't need any precomputed tables.

**Comment by rkralovic** [comment]
On Sat, Mar 9, 2019 at 4:29 PM HPS <notifications@github.com> wrote:

> Well, for N=12 (block size 4096, which is reasonable to achieve reasonable
> bass resolution) it is already 12*4096=49k vs. 3**12=531k - more than 10x.
> And I am still not convinced that there are actually any accuracy gains.
> (Perhaps I should try to compare both approaches and see if the output is
> exactly the same.)
>
> You forgot that FFT uses 4x number of multiplications.
>
> 4 * 12 * 4096=196k VS 3**12=531k SO roughly 2x. And I don't need any
> precomputed tables.
>
> Whatever :-). I'll try the ioctl when it is there and check if the
performance is acceptable.

**Comment by hselasky** [comment]
Hi,

Can you update to my latest virtual_oss and virtual_oss_ctl in github and then run, where dsp3 is your audio device:

1) virtual_oss -C 2 -c 2 -r 48000 -b 16 -s 50.0ms -F 2048 -G 2048 -f /dev/dsp3 -d vdsp -t vdsp.ctl
2) virtual_oss_ctl -f /dev/vdsp.ctl

Press the EQ button. Can you help out a bit with the FIR filter generation? See:
https://github.com/hselasky/virtual_oss_ctl/blob/master/virtual_oss_ctl_equalizer.cpp

--HPS

**Comment by rkralovic** [comment]
Thanks, I'll have a look!

**Comment by rkralovic** [comment]
Hello,

1) I didn't managed to get virtual_oss_ctl working in reasonable time:
since I run it on a server with no X and no dbus, it didn't work. (I set up
X forwarding, but hesitated to install dbus, which is imho ugly :-) ).

2) The backend worked nicely:
virtual_oss -C 2 -c 2 -S -Q 0 -b 32 -r 48000 -s 5ms -F 4096 -G 4096 -R
/dev/null -P /dev/dsp -d dsp.virtual -t vdsp.ctl

I made a simplified version of the equalizer I used so far:
https://github.com/rkralovic/virtual_oss/blob/builtin/equalizer.c
Compile with
cc -I/usr/local/include -L/usr/local/lib -O3 -Wall -W -o equalizer
equalizer.c -lm -lfftw3 -lpthread
and test with
./equalizer -b 4096
nc -uU -w0 /tmp/equalizer.socket <<EOF
199 0.0
200 1.0
400 1.0
401 0.0
EOF

(There is no real reason to keep the socket interface, but I just didn't
have time to remove it yet.)

This sets up a FIR filter that implements linear-phase equalizer, that is,
it does not shift phases of different frequencies, but it introduces more
latency.

3) Would you agree to make /dev/null input non-blocking (i.e., set
voss_has_synchronization=1) if there is a non-null output, like I had it in
my original patch? Otherwise, there is again the problem with clock drifts.

    Richard

**Comment by hselasky** [comment]
> 3)  Would you agree to make /dev/null input non-blocking (i.e., set voss_has_synchronization=1) if there is a non-null output, like I had it in my original patch? Otherwise, there is again the problem with clock drifts. Richard

I though this was already the case. Can you send me a patch for that?

I'll have a look at your equalizer.c probably later this week. Depends on how much other work I have.

--HPS

**Comment by hselasky** [comment]
Never mind. I figured it out looking at your examples. Can you try the latest version of virtual_oss from master branch?
PS: I made some modifications to your code. Please review!

**Comment by rkralovic** [comment]
On Wed, Mar 13, 2019 at 1:25 PM HPS <notifications@github.com> wrote:

> Never mind. I figured it out looking at your examples. Can you try the
> latest version of virtual_oss from master branch?
> PS: I made some modifications to your code. Please review!
>
Thanks! From a quick look and a quick test, it looks good, except for the
FIR normalization: It does change volume significantly, and I don't think
it is correct: Requiring sum of the filter to be = 1 means that a constant
1 will not be modified. However, constant 1 in frequency domain is
frequency 0 with amplitude 1 and no other frequencies. If we have a filter
that passes only a given narrow frequency range, it is expected to get 0 as
an output.

I'd suggest to drop it altogether, so the user-specified values for
amplification/attenuation of given frequencies are honored exactly.

I'll be travelling for the next couple of days, I'll get to more tests when
I'm back.

    Richard

**Comment by hselasky** [comment]
> I'd suggest to drop it altogether, so the user-specified values for
amplification/attenuation of given frequencies are honored exactly.

The problem is that certain inputs will cause the output to overflow and then the limiter kicks in.

Maybe we can add an option to not do normalization?

**Comment by rkralovic** [comment]
Dňa št 14. 3. 2019, 8:43 HPS <notifications@github.com> napísal(a):

> I'd suggest to drop it altogether, so the user-specified values for
> amplification/attenuation of given frequencies are honored exactly.
>
> The problem is that certain inputs will cause the output to overflow and
> then the limiter kicks in.
>
Normalization in the current form doesn't help - a single-frequency pass
filter have sum almost 0, but still can amplify that frequency arbitrarily.

On the other hand, I don't think an overflow can happen if all frequencies
are attenuated, i.e., the user specifies no boosts >1.

Maybe we can add an option to not do normalization?
>

If you want normalization, I think it should be done in frequency domain:
divide all boosts by maximal one, so that no boost is >1. Maybe that could
be an option in virtual_equalizer. But having the ability to actually boost
the volume looks like a good thing to me.

**Comment by hselasky** [comment]
OK,

See here https://github.com/hselasky/virtual_oss/commit/62d208bc533443d7f8b07cafb914ce105fc171ac .

I'm closing this pull request, now the feature has been implemented.

Thank you!

**Comment by rkralovic** [comment]
Thanks!

**Pull request closed without merging**
