### PR TITLE
Synchronization via client clocks

### PR DESCRIPTION
**Pull request by rkralovic**
Hello,

I am using virtual_oss with null backend for mixing inputs and the output is processed by an equalizer and sent to the soundcard. In that setup, I got regular buffer underruns, since the null backend uses real clock for timing, which slightly diverges from the soundcard clock.

I think the proper fix is to allow a client device to be used for synchronization: A given client device can be marked as synchronized and virtual_oss then waits until clients read/write data from that device. Null backend should not block if there is a synchronized client.

I implemented this in the following patch. Do you think this is the right approach?

### CODE REVIEW

**Comment by hselasky** [comment]
Hi, I'll have a look tomorrow or later this week. Thank you for your patch!

**Comment by hselasky** [comment]
Hi, Can you try this patch instead?

[virtual_oss_diff.txt](https://github.com/hselasky/virtual_oss/files/2929998/virtual_oss_diff.txt)

--HPS

**Comment by rkralovic** [comment]
Hello,

Thanks, that one works fine, too!

Actually, I thought that allowing multiple synchronized profiles can be
useful: if the sink uses significantly larger buffer than the source and
the source, having both source and sink synchronized is a clean way to
avoid any buffer overruns / underruns.

But I see that this makes things more complicated and harder to understand,
and probably it is not too important neither (if the sink uses small
buffer, there is no need for this). So I am fine with both ways.

Greets,
    Richard

**Comment by hselasky** [comment]
I've pushed this upstream with some minor modifications. Please submit a new pull request if more changes are needed.

Thank you!

**Comment by hselasky** [comment]
> Actually, I thought that allowing multiple synchronized profiles can be useful: if the sink uses significantly larger buffer than the source and the source, having both source and sink synchronized is a clean way to avoid any buffer overruns / underruns.

Could you give some examples how you are using this feature?

Are the applications using the -L xxx devices synchronized somehow?

**Comment by rkralovic** [comment]
On Thu, Mar 7, 2019 at 7:34 PM HPS <notifications@github.com> wrote:

> Actually, I thought that allowing multiple synchronized profiles can be
> useful: if the sink uses significantly larger buffer than the source and
> the source, having both source and sink synchronized is a clean way to
> avoid any buffer overruns / underruns.
>
> Could you give some examples how you are using this feature?
>
> Are the applications using the -L xxx devices synchronized somehow?
>
Currently I am using your submitted version; it works well, thanks!

With my patch (the one with -x instead of -L), I was using:
virtual_oss -S -Q 0 -b 32 -c 2 -r 48000 -s 5ms -i 20 -f /dev/null -x -d
dsp.virtual -x -l dsp.virtual_out -B

I was running an equalizer reading from dsp.virtual_out:
equalizer -i /dev/dsp.virtual_out -o /dev/dsp -r 48000 -b 4096 -B

Players (musicpd and virtual_bt_speaker) were using dsp.virtual:
virtual_bt_speaker -B -d /dev/dsp.virtual

My concern was that if the equalizer uses large buffer (~100ms), it would
read the whole buffer as fast as it can (~50ms due to nice sleeps in
virtual_oss). If bt_speaker has smaller buffer than 50ms, it would suffer
an underrun unless dsp.virtual is marked as synchronized (-x).

With both dsp.virtual and dsp.virtual_out marked synchronized, there is no
risk of buffer underruns. This setup relies on the fact that all players
are well behaved (they either outputs sound at realtime speed or they close
the dsp device). If any of the clients is not behaving well (opens dsp
device and does not output anything), it would block all others (but in my
setup I use only musicpd and virtual_bt_speaker and they are both ok).

    Richard

**Comment by hselasky** [comment]
Is this equalizer program available somewhere? I could easily integrate it within virtual_oss, and then you could control it via virtual_oss_ctl .

**Comment by rkralovic** [comment]
On Fri, Mar 8, 2019 at 9:27 AM HPS <notifications@github.com> wrote:

> Is this equalizer program available somewhere? I could easily integrate it
> within virtual_oss, and then you could control it via virtual_oss_ctl .
>
I have just committed it to my virtual_oss clone (
https://github.com/rkralovic/virtual_oss/tree/equalizer) and sent you a
pull request.

It seems to me that keeping it as a separate binary is cleaner: In this
implementation, I have sacrificed latency to achieve precise control over
frequency response. That probably doesn't suit all use cases. But if you
think that tighter integration makes sense, we can try that.

     Richard

**Pull request closed without merging**
